### ISSUE TITLE
Review missing OKR metrics

### ISSUE THREAD

**Issue by moliva** [decentraland/matrix-playbook#15]
- Possibly add metrics in Kernel for failed connections to Chat & Friends

**Comment by moliva** [comment]
[Metrics implemented on Explorer side](https://www.notion.so/decentraland/1ab70141466e4a8d83ddd9cef6f7e414?v=f46b513dd3ee4620901fe1231feedf1a)

**Comment by guidota** [comment]
At the moment we can check some metrics in Metabase:
- Initialization (login)
- Send private messages
