### ISSUE TITLE
Make Redis instance configurable in playbook

### ISSUE THREAD

**Issue by moliva** [decentraland/matrix-playbook#29]

**Comment by guidota** [comment]
Done:

- https://dcl.tools/ops/synapse-redis
- https://dcl.tools/ops/synapse-test-server/-/commit/317b62ad69aaf819d69a0f6150c13028615ced7c
- https://dcl.tools/ops/synapse-test-server/-/commit/dd02e8a17f2fdb031338d05f61997b0868373c10
- https://github.com/decentraland/matrix-playbook/pull/33
