### ISSUE TITLE
Review worker affinity in prd

### ISSUE THREAD

**Issue by moliva** [decentraland/matrix-playbook#40]
Review which header can be used or must be generated.

**Comment by guidota** [comment]
We can use the `authorization` header as described in [synapse docs](https://matrix-org.github.io/synapse/latest/workers.html#load-balancing)

**Comment by guidota** [comment]
We can use the `authorization` header as described in [synapse docs](https://matrix-org.github.io/synapse/latest/workers.html#load-balancing)
